# core/scanner/manager_icmp.py
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from main import Tools
    from core.secretary import Secretary
    from core.network.network_manager import NetworkSnapshot

from collections import defaultdict
from typing import Any
import json # TODO del it in realise. It's for debug

from core.enums import EvtType, Priority, TickInterval, SpeedShiftICMP
from core.protocol import Frame
from core.scanner import ScannerICMP
from core.secretary import Secretary
from core.logger import Logger


class ManagerICMP():
    SCAN_QUEUE_THRESHOLD = 20 # TODO move it to config in future

    def __init__(self, tools: Tools, secr: Secretary, logger: Logger) -> None:
        self._tools: Tools = tools
        self._secr: Secretary = secr
        self._log: Logger = logger
        
        self._scanner: ScannerICMP = ScannerICMP()
        
        self._snapshot: NetworkSnapshot = None

        min_interval = TickInterval.SEC_05.value
        max_interval = TickInterval.SEC_8.value
        self._intervals = [t for t in TickInterval if min_interval <= t.value <= max_interval]
        self._speed_shift: SpeedShiftICMP = SpeedShiftICMP.NORM
        self._tick_schedule = self._prepare_schedule()
        self._interval_groups: dict[TickInterval, list[dict[str, any]]] = None
        print(json.dumps(self._tick_schedule, indent=4, default=str)) # TODO del it in realise


    def _prepare_schedule(self) -> dict:
        """
        Creates a nested schedule map:
        full_map[SpeedShiftICMP][EvtType] -> [TickInterval, ...] 
        In the lists: [longest_interval, ..., shortest_inteval]
        Logic: Shifts the group's effective interval index based on the speed multiplier
        and checks if the current physical tick is a multiple of that interval.
        """
        # Mapping: Physical Tick Event -> Physical Interval Value
        tick_to_int = {
            EvtType.TICK_05: TickInterval.SEC_05,
            EvtType.TICK_1:  TickInterval.SEC_1,
            EvtType.TICK_2:  TickInterval.SEC_2,
            EvtType.TICK_4:  TickInterval.SEC_4,
            EvtType.TICK_8:  TickInterval.SEC_8,
        }
        full_map = {}

        # Iterate through speed modes: FAST (1), NORM (0), LOW (-1)
        for shift in SpeedShiftICMP:
            shift_map = {}
            
            # Process each physical tick generated by the Ticker
            for phys_evt, phys_int in tick_to_int.items():
                active_groups = []
                
                # Check each device group (by their base interval)
                for group_int in reversed(self._intervals):
                    # 1. Find the base interval index in the "rails" [0.5 ... 8.0]
                    idx = self._intervals.index(group_int)
                    
                    # 2. Apply shift: FAST(1) -> idx-1 (faster), LOW(-1) -> idx+1 (slower)
                    # Clamping the index within available interval bounds
                    new_idx = max(0, min(idx - shift.value, len(self._intervals) - 1))
                    
                    # 3. Determine the effective interval for the current speed mode
                    effective_int = self._intervals[new_idx]
                    
                    # 4. Check if the physical tick aligns with the effective interval
                    # Using small epsilon for float modulo safety
                    if (phys_int.value + 0.001) >= effective_int.value and \
                       (phys_int.value % effective_int.value) < 0.01:
                        active_groups.append(group_int)
                
                shift_map[phys_evt] = active_groups
            
            full_map[shift] = shift_map
            
        return full_map

    # --- On events ---
    def _on_speed_changed(self, frame: Frame) -> None: # ICMP_NEW_INTERVALS
        """Speed mode change event."""
        self._speed_shift = frame.payload["icmp_speed_shift"]
        
    def _on_tick(self, frame: Frame) -> None: # TICK_* (05-8)
        """Send data from scaner to buffer and put to scanner new job"""
        tick_type = frame.evt_type
        tick_id = frame.payload["tick_id"]
        scan_results = self._scanner.pop_results()
        # Check scan queue overloaded
        queue_depth = self._scanner.get_queue_depth()
        if self._scanner.get_queue_depth() > self.SCAN_QUEUE_THRESHOLD: # TODO move to gonfig
            text = f"Scan skip at tick {tick_id}. Queue overloaded: {queue_depth} tasks."
            self._log.wrn(text)
            return
        scan_queue = []
        for intervel in self._tick_schedule[self._speed_shift][tick_type]:
            scan_queue += self._interval_groups[intervel]
        self._scanner.execute(scan_queue, tick_id)
        payload = {"data": scan_results}
        self._secr.send_evt(EvtType.ICMP_SCAN_RAW_DATA_READY, payload=payload)

    def _on_new_net_ver(self, frame: Frame) -> None: # ICMP_BUF_NEW_NET_VER_READY / NETWORK_NEW_VER
        """checks net ver and build new sorted _interval_groups."""
        frame_snapshot = frame.payload.get("snapshot", None)
        if not frame_snapshot:
            self._log.err("payloadd with out 'snapshot'", frame, "SMe")
            return
        if frame_snapshot.version < self._tools.network.snapshot.version:
            return # Wait new evt new net ver
        elif frame_snapshot.version > self._tools.network.snapshot.version:
            text = "The version received is newer than the network version."
            self._log.err(text, frame, "SMe")
            return
        else:
            self._get_interval_groups_by_net_tab(frame_snapshot.tab)
            self._sort_interval_groups()

    def _on_ready_uids_by_latency(self, frame: Frame) -> None: # ICMP_UIDS_BY_LATENCY_READY
        """gets uids_by_latency from BufferICMP"""
        temp_score = frame.payload.get("uids_by_latency", None)
        if not temp_score:
            self._log.err("uids_by_latency was not applied", frame, "Se")
            return
        self._uids_by_latency = temp_score
        self._sort_interval_groups()

    def _get_interval_groups_by_net_tab(self, tab: dict[int, dict[str, Any]]) -> None:
        """
        Groups devices from the network table by their scan intervals.
        Args: tab: Dictionary where key is UID and value is device data.
        Returns: Dictionary where key is TickInterval and value is a list of device dicts.
        """
        # Use defaultdict to automatically initialize empty lists for new keys
        groups = defaultdict(list)
        for uid, dev_data in tab.items():
            # Retrieve the interval object (TickInterval)
            interval = dev_data.get("icmp_scan_interval")
            if interval:
                # Append device data to the corresponding interval bucket
                groups[interval].append(dev_data)
        # Convert back to regular dict for consistency with the rest of the core
        self._interval_groups = dict(groups)

            
    def _sort_interval_groups(self) -> None:
        """sorts all lists in _interval_groups by margin and latency"""
        for uid_list in self._interval_groups:
            pass
